### ISSUE TITLE
How to run this project locally?

### ISSUE THREAD

**Issue by rdrsadhu** [ansin218/swift-airline-reservation-system-php-mysql#1]
After cloning what are the steps to be followed, to run this project in my local machine.

Also, what software/dependencies need to be preinstalled?

Thank you.

**Comment by ansin218** [comment]
I did this a few years back bro. I do not remember. If I find my project report, I shall send it to you. Will that be alright?

**Comment by rdrsadhu** [comment]
Yes please. That would surely help.

**Comment by ansin218** [comment]
Documentation report has been added.
